project:
  type: website

lang: es

website:
  google-analytics: '{{ env.GA_TRACKING_ID }}'
  title: "Patricio Said"
  favicon: logo.png
  navbar:
    logo: logo.png
    right:
      - blog.qmd
      - text: Email
        icon: envelope
        url: "mailto:psaidp2@gmail.com"
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute:
  freeze: true


