project:
  type: website

lang: es

website:
  google-analytics: 
    tracking-id: '{{< env GA_TRACKING_ID >}}'
  title: "Patricio Said"
  description: "blog de Patricio Said (Patosaid), ciencia de datos, R Python programacion, gráficas, plots, dashboard"
  favicon: logo.png
  margin-footer: "Creado por Pato Said con Quarto, 2024"
  navbar:
    logo: logo.png
    right:
      - blog.qmd
      - text: Email
        icon: envelope
        url: "mailto:psaidp2@gmail.com"
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute:
  freeze: true


