project:
  type: website

lang: es

website:
  google-analytics: 
    tracking-id: '{{ env.GA_TRACKING_ID }}'
  title: "Patricio Said"
  description: "blog de Patricio Said (Patosaid patricio said peralta), ciencia de datos, R Python programacion, gráficas, plots, dashboard"
  favicon: logo.png
  navbar:
    logo: logo.png
    right:
      - blog.qmd
      - text: Email
        icon: envelope
        url: "mailto:psaidp2@gmail.com"
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - includes/umami.html
      - includes/google.html

editor: visual

execute:
  freeze: true


