project:
  type: website

lang: es

website:
  title: "Patricio Said"
  navbar:
    right:
      - blog.qmd
      - text: Email
        icon: envelope
        url: "mailto:psaidp2@gmail.com"
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

execute:
  freeze: true


